export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  UPDATE_ONLINE_USER: "UPDATE_ONLINE_USER",
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_SEARCH_USERS: "SET_SEARCH_USERS",
};
